# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=100)),
                ('type_area', models.CharField(choices=[('small', 'small'), ('middle', 'middle'), ('large', 'large')], max_length=7)),
                ('name_master', models.CharField(max_length=100)),
                ('date_area', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
