# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GameList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmaster',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pause', 'Pause'), ('Finished', 'Finished')], default=datetime.datetime(2016, 8, 11, 12, 18, 29, 405000, tzinfo=utc), max_length=7),
            preserve_default=False,
        ),
    ]
